<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\AspireOutboxDemo\AspireOutboxDemo.ServiceDefaults\AspireOutboxDemo.ServiceDefaults.csproj" />
	  <ProjectReference Include="..\Infra\Infra.csproj" />
	</ItemGroup>
</Project>