<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.5.4" />
    <PackageReference Include="CommunityToolkit.Aspire.MassTransit.RabbitMQ" Version="13.5.0" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.5" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireOutboxDemo\AspireOutboxDemo.ServiceDefaults\AspireOutboxDemo.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Infra\Infra.csproj" />
  </ItemGroup>

</Project>
